name: GitHub Release with APKs

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 45

    steps:
      - name: Checkout
        uses: actions/checkout@v3   

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Copy CI gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11

      - name: Build app
        run: ./gradlew :app:assembleProdRelease 

      - uses: actions/upload-artifact@v3
        with:
          name: my-apk
          path: app/build/outputs/apk/prod/release/app-prod-release.apk  

      - uses: actions/upload-artifact@v3
        with:
          name: my-aab
          path: app/build/outputs/bundle/prodRelease/app-prod-release.aab    
